### ISSUE TITLE
How to deploy seq2seq model in tf serving?

### ISSUE THREAD

**Issue by shawnlix** [psyfb2/Chatbot#1]
Hi Fady,

I noticed the issue you raised at https://github.com/tensorflow/serving/issues/1607, and realized I have the exact confusion as you described. I'm wondering have you been able to figure out how to deploy a seq2seq models using TensorFlow serving? If so, could you please share some pointers on how to do that? Thank you!

**Comment by psyfb2** [comment]
I did deploy Seq2Seq and Transformer models on Flask using Google App Engine. The website was up for some time but due to a lack of funds I couldn't keep it up since the models used around 4GB of RAM which wasn't on the free tier of Google App Engine. I didn't use Tensorflow Serving because its very limited in preprocessing capabilities (setting up a tokenizer isn't easy, regular expressions and so on). On top of this it would have incurred an extra cost to host on a VM so I couldnt do this. Instead I just directly used the models in Flask, you can see the source code for this in the main.py file.

**Comment by shawnlix** [comment]
Thank you for the explanation!
